# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# GET room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/4ab99cd2-e2c8-421b-ad41-2d9fa3570cc8/questions
Content-Type: application/json

{
    "question": "O que é React?"
}